### ISSUE TITLE
RFC: Groups of interfaces

### ISSUE THREAD

**Issue by dorezyuk** [EVerest/EVerest-archived#225]
Hi, this is more a RFC than a feature request. So feel free do discuss 

```yaml
# the manifest of a module
requires:
    evse:
      interface: evse_manager
      min_connections: 0
      max_connections: 2      
    power_meter:
      interface: powermeter
      min_connections: 0
      max_connections: 2 
```
I've often following use case. Consider the manifest above. We say that the module can have 0-2 connections to the `evse_manager` and 0-2 connections to the `powermeter`. Now what I actually want to say is that the number of connections to the `evse_manager` should match the number of connections of the `powermeter`. My proposal would be to extend the syntax of a manifest to something like

```yaml
requires:
  group:
    name: some group
    min_connections: 0
    max_connections: 2      
    evse:
      interface: evse_manager
    power_meter:
      interface: powermeter 
```
to be able to express the that some interfaces should be provided together
